from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.user_logout, name='logout'), 
    path('article/', views.article_view, name='article'),
    path('content/', views.content_view, name='content'),
    path('blog/', views.blog_view, name='blog'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('about/', views.about, name='about'),
    path('like/<int:article_id>/', views.like_article, name='like_article'),
    path('add-comment/<int:article_id>/', views.add_comment, name='add_comment'),    path('edit/<int:article_id>/', views.edit_article, name='edit_article'),
    path('delete/<int:article_id>/', views.delete_article, name='delete_article'),
    path('like-blog/<int:blog_id>/', views.like_blog, name='like_blog'),
    path('edit-blog/<int:blog_id>/', views.edit_blog, name='edit_blog'),
    path('delete-blog/<int:blog_id>/', views.delete_blog, name='delete_blog'),
    path('like-content/<int:content_id>/', views.like_content, name='like_content'),
    path('edit-content/<int:content_id>/', views.edit_content, name='edit_content'),
    path('delete-content/<int:content_id>/', views.delete_content, name='delete_content'),
    path('blog-comment/<int:blog_id>/', views.add_blog_comment, name='add_blog_comment'),
    path('content-comment/<int:content_id>/', views.add_content_comment, name='add_content_comment'),
    path('hire/<int:user_id>/', views.hire_writer, name='hire_writer'),
    path('chat/<int:chat_id>/', views.chat_page, name='chat_page'),
    path('send/<int:chat_id>/', views.send_message, name='send_message'),
    path('get-messages/<int:chat_id>/', views.get_messages, name='get_messages'),
    path('inbox/', views.inbox, name='inbox'),
    path('requests/', views.writer_requests, name='writer_requests'),
    path('handle-request/<int:request_id>/<str:action>/', views.handle_request, name='handle_request'),
    path('writers/', views.writers_list, name='writers'),
    path('review/<int:writer_id>/', views.add_review, name='add_review'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('hired-writers/',views.hired_writers,name='hired_writers'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='main/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm.html'),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(    template_name='main/password_reset_complete.html'),name='password_reset_complete'),
]