# Generated by Django 5.2.8 on 2026-04-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
    ]
