# Generated by Django 5.2.8 on 2026-04-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_article_likes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
